### ISSUE TITLE
Unzip added as part of the script

### ISSUE THREAD

**Issue by tom472** [cmartello/hunter#4]
Would it also be useful to add unzipping the Yawgatog Oracle text file directly into the Python script?
This page might be helpful: http://lists.canonical.org/pipermail/kragen-hacks/2002-February/000322.html

**Comment by cmartello** [comment]
It could be done, but I don't think it's a huge deal at this time.  Unzipping a file ought to be fairly trivial for most users.  Right now, I'm more focused on making sure that the actual file is read correctly.

**Comment by tom472** [comment]
Agreed its pretty simple but in the future could be nice to have a single script that does it all.
