### ISSUE TITLE
some cards are not parsing

### ISSUE THREAD

**Issue by cmartello** [cmartello/hunter#5]
The "All Sets" file seems to introduce some unforeseen irregularities.  First immediate problem is "Tezzeret the Seeker" does not appear in the output database.

He appears in the original text right after a Vanguard card.  Perhaps this messes with the logic.

**Comment by tom472** [comment]
OK tested again with the Vintage zip file renamed as oracle.txt
Got this:

<pre> sqlite3 oracle.db "select * from cards" | wc -l
28753</pre>

and then this:

<pre>sqlite3 oracle.db "select cardid,cardname from cards where cardname like 'Tezz%'"
9630|Tezzeret the Seeker</pre>

Almost exactly 100 rows higher than your result.
Wonder what our differences are coming from.

**Comment by cmartello** [comment]
I was using an out of date Vintage.txt for one; the difference was basically the new M11 cards.

Incidentally, I found that selecting \* gives every linebreak (such as those in the card rules) and can give unpredictable results.  Further sanity testing is probably better done like so :

<pre>

[19:44:52 cmartello@europa:pts/0:~/code/hunter] 
% grep -c '^$' Vintage-2010-08-01.txt 
11094
[19:50:32 cmartello@europa:pts/0:~/code/hunter] 
% sqlite3 Vintage-2010-08-01.db 'select cardid,cardname from cards' | wc -l
11094
</pre>
